language: python
sudo: false

python:
  - "3.6.2"

install: 
  - "pip install -r test_requirements.txt"
  - "pip install --no-deps ."

script:
  - nosetests-3.4 --with-coverage --cover-package dino -s test
  - coverage-3.5 report --omit=env -m

after_success:
  - codecov
