language: python
sudo: false

python:
  - "3.5"

install: 
  - "pip install -r test_requirements.txt"

script:
  - nosetests-3.4 --with-coverage --cover-package dino -s test
  - coverage-3.5 report --omit=env -m

after_success:
  - codecov
